In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive
/gdrive


In [2]:
pip install tensorflow-gpu==2.0.0

     |████████████████████████████████| 380.8MB 37kB/s 
     |████████████████████████████████| 450kB 45.2MB/s 
     |████████████████████████████████| 3.8MB 41.7MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp36-none-any.whl size=7540 sha256=acebd4a5577b451073b7986269654533b2c226a536ad180e264d6bbd8134b8f4
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow 2.2.0rc3 has requirement gast==0.3.3, but you'll have gast 0.2.2 which is incompatible.
ERROR: tensorflow 2.2.0rc3 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 2.0.2 which is incompatible.
ERROR: tensorflow 2.2.0rc3 has requirement tensorflow-estimator<2.3.0,>=2.2.0rc0, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
ERROR: tensorflow-probability 0.10.0rc0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.2

In [3]:
pip install keras==2.2.4

     |████████████████████████████████| 317kB 3.5MB/s eta 0:00:01
  Found existing installation: Keras 2.3.1
    Uninstalling Keras-2.3.1:
      Successfully uninstalled Keras-2.3.1


In [4]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Select the Runtime → "Change runtime type" menu to enable a GPU accelerator, ')
  print('and then re-execute this cell.')
else:
  print(gpu_info)

Fri Apr 24 19:34:45 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    30W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [5]:
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img
import numpy as np
import argparse
import cv2
import os
from imutils import paths

Using TensorFlow backend.


In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.resnet_v2 import ResNet152V2
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import argparse
import cv2
import os

In [ ]:
x_train=np.load('My Drive/Colab Notebooks/215-FP_Dataset/numpy5/x_train.npy')

In [ ]:
y_train=np.load('My Drive/Colab Notebooks/215-FP_Dataset/numpy5/y_train.npy')

array([[0.     , 0.00392],
       [0.     , 0.00392],
       [0.     , 0.00392],
       ...,
       [0.     , 0.00392],
       [0.     , 0.00392],
       [0.     , 0.00392]], dtype=float16)

In [24]:
y_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
x_valid=np.load('My Drive/Colab Notebooks/215-FP_Dataset/numpy5/x_valid.npy')

In [ ]:
y_valid=np.load('My Drive/Colab Notebooks/215-FP_Dataset/numpy5/y_valid.npy')

In [27]:
y_valid

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
y_train2=y_train
y_valid2=y_valid

In [ ]:
y_train2=np.argmax(y_train,axis=1)
y_valid2=np.argmax(y_valid,axis=1)

In [30]:
y_train2[:50]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1])

In [31]:
y_valid2[:50]

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1])

In [34]:
summation1=0
for i in range(len(x_valid)):
    if y_valid2[i]==0:
        summation1=summation1+1
summation1

488

In [35]:
summation2=0
for i in range(len(x_train)):
    if y_train2[i]==0:
        summation2=summation2+1
summation2

1951

In [36]:
len(x_train)

6025

In [ ]:
#y_train=y_train2
y_train=((y_train)/255.).astype('float16')

In [ ]:
#y_valid=y_valid2
y_valid=((y_valid)/255.).astype('float16')

In [44]:
from __future__ import print_function
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Layer
from tensorflow.keras import activations
from tensorflow.keras import utils
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import keras
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras import optimizers

K.set_image_data_format('channels_last')

def squash(x, axis=-1):
    s_squared_norm = K.sum(K.square(x), axis, keepdims=True) + K.epsilon()
    scale = K.sqrt(s_squared_norm) / (1 + s_squared_norm)
    return scale * x


def softmax(x, axis=-1):
    
    ex = K.exp(x - K.max(x, axis=axis, keepdims=True))
    return ex / K.sum(ex, axis=axis, keepdims=True)


def margin_loss(y_true, y_pred):
    
    lamb, margin = 0.5, 0.1
    return K.sum((y_true * K.square(K.relu(1 - margin - y_pred)) + lamb * (
        1 - y_true) * K.square(K.relu(y_pred - margin))), axis=-1)


class Capsule(Layer):
   

    def __init__(self,
                 num_capsule,
                 dim_capsule,
                 routings=3,
                 share_weights=True,
                 activation='squash',
                 **kwargs):
        super(Capsule, self).__init__(**kwargs)
        self.num_capsule = num_capsule
        self.dim_capsule = dim_capsule
        self.routings = routings
        self.share_weights = share_weights
        if activation == 'squash':
            self.activation = squash
        else:
            self.activation = activations.get(activation)
            
    def get_config(self):
        config = super().get_config().copy()
        config.update({
        'num_capsule':  self.num_capsule,
        'dim_capsule' : self.dim_capsule,
        'routings':  self.routings,
        'share_weight':self.share_weights,
        
       
           
        })
        return config

    def build(self, input_shape):
        input_dim_capsule = input_shape[-1]
        if self.share_weights:
            self.kernel = self.add_weight(
                name='capsule_kernel',
                shape=(1, input_dim_capsule,
                       self.num_capsule * self.dim_capsule),
                initializer='glorot_uniform',
                trainable=True)
        else:
            input_num_capsule = input_shape[-2]
            self.kernel = self.add_weight(
                name='capsule_kernel',
                shape=(input_num_capsule, input_dim_capsule,
                       self.num_capsule * self.dim_capsule),
                initializer='glorot_uniform',
                trainable=True)

    def call(self, inputs):
        

        if self.share_weights:
            hat_inputs = K.conv1d(inputs, self.kernel)
        else:
            hat_inputs = K.local_conv1d(inputs, self.kernel, [1], [1])

        batch_size = K.shape(inputs)[0]
        input_num_capsule = K.shape(inputs)[1]
        hat_inputs = K.reshape(hat_inputs,
                               (batch_size, input_num_capsule,
                                self.num_capsule, self.dim_capsule))
        hat_inputs = K.permute_dimensions(hat_inputs, (0, 2, 1, 3))

        b = K.zeros_like(hat_inputs[:, :, :, 0])
        for i in range(self.routings):
            c = softmax(b, 1)
            o = self.activation(keras.backend.batch_dot(c, hat_inputs, [2, 2]))
            if i < self.routings - 1:
                b = keras.backend.batch_dot(o, hat_inputs, [2, 3])
                if K.backend() == 'theano':
                    o = K.sum(o, axis=1)

        return o

    def compute_output_shape(self, input_shape):
        return (None, self.num_capsule, self.dim_capsule)




batch_size = 16  
num_classes = 2
epochs = 100




#class weights to handle class imbalance

#class_weights = {0: 1-np.count_nonzero(y_train==0)/len(y_train),
            #    1: 1-np.count_nonzero(y_train==1)/len(y_train)} 



input_image = Input(shape=(None, None, 3))
x = Conv2D(64, (3, 3), activation='relu',trainable = False)(input_image)
x=BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True, beta_initializer='zeros', gamma_initializer='ones', moving_mean_initializer='zeros', moving_variance_initializer='ones', beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None)(x)
x = Conv2D(64, (3, 3), activation='relu',trainable = False)(x)
x = AveragePooling2D((2, 2),trainable = False)(x)
x = Conv2D(128, (3, 3), activation='relu',trainable = False)(x)
x = Conv2D(128, (3, 3), activation='relu',trainable = False)(x)




x = Reshape((-1, 128))(x)
x = Capsule(32, 8, 3, True)(x)  
x = Capsule(32, 8, 3, True)(x)   
capsule = Capsule(5, 16, 3, True)(x)
output = Lambda(lambda z: K.sqrt(K.sum(K.square(z), 2)))(capsule)




model = Model(inputs=[input_image], outputs=[output])

model.load_weights('My Drive/Colab Notebooks/215-FP_Dataset/pre-train.h5')

capsule2 = Capsule(2, 16, 3, True)(model.layers[-3].output)
output2 = Lambda(lambda z: K.sqrt(K.sum(K.square(z), 2)))(capsule2)


model2 = Model(inputs=[input_image], outputs=[output2])


adam = optimizers.Adam(lr=0.001) 
model.compile(loss=margin_loss, optimizer=adam, metrics=['accuracy'])
model2.compile(loss=margin_loss, optimizer=adam, metrics=['accuracy'])
model2.summary()

data_augmentation = False
# The best model is selected based on the loss value on the validation set


filepath='My Drive/Colab Notebooks/215-FP_Dataset/after-train.h5'
checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]





if not data_augmentation:
    print('Not using data augmentation.')
    model2.fit(
        [x_train], [y_train],
        batch_size=batch_size,
        epochs=epochs,
        validation_data=[[x_valid], [y_valid]],
        shuffle=True,callbacks=callbacks_list)
    
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by dataset std
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        zca_epsilon=1e-06,  # epsilon for ZCA whitening
        rotation_range=0.1,  # randomly rotate images in 0 to 180 degrees
        width_shift_range=0.1,  # randomly shift images horizontally
        height_shift_range=0.1,  # randomly shift images vertically
        brightness_range=[0.5,1.5],
        shear_range=0.1,  # set range for random shear
        zoom_range=0.1,  # set range for random zoom
        channel_shift_range=0.,  # set range for random chann el shifts
        # set mode for filling points outside the input boundaries
        fill_mode='nearest',
        cval=0.,  # value used for fill_mode = "constant"
        horizontal_flip=True,  # randomly flip images
        vertical_flip=True,  # randomly flip images
        # set rescaling factor (applied before any other transformation)
        rescale=None,
        # set function that will be applied on each input 
        preprocessing_function=None,
        # image data format, either "channels_first" or "channels_last"
        data_format=None,
        # fraction of images reserved for validation (strictly between 0 and 1)
        validation_split=0.0)

    # Compute quantities required for feature-wise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_train)

    # Fit the model on the batches generated by datagen.flow().
    model.fit(
        datagen.flow(x_train, y_train, batch_size=batch_size),
        epochs=epochs,
        validation_data=(x_valid, y_valid),shuffle=True)

Model: "model_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, None, None, 3)]   0         
_________________________________________________________________
conv2d_36 (Conv2D)           (None, None, None, 64)    1792      
_________________________________________________________________
batch_normalization_9 (Batch (None, None, None, 64)    256       
_________________________________________________________________
conv2d_37 (Conv2D)           (None, None, None, 64)    36928     
_________________________________________________________________
average_pooling2d_9 (Average (None, None, None, 64)    0         
_________________________________________________________________
conv2d_38 (Conv2D)           (None, None, None, 128)   73856     
_________________________________________________________________
conv2d_39 (Conv2D)           (None, None, None, 128)   147

In [ ]:
batch_size = 16  
num_classes = 2
epochs = 100     



x_test=  x_valid
y_test=  y_valid







#model: model without pre-training

input_image = Input(shape=(None, None, 3))
x = Conv2D(64, (3, 3), activation='relu')(input_image)
x=BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True, beta_initializer='zeros', gamma_initializer='ones', moving_mean_initializer='zeros', moving_variance_initializer='ones', beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None)(x)
x = Conv2D(64, (3, 3), activation='relu')(x)
x = AveragePooling2D((2, 2))(x)
x = Conv2D(128, (3, 3), activation='relu')(x)
x = Conv2D(128, (3, 3), activation='relu')(x)




x = Reshape((-1, 128))(x)
x = Capsule(32, 8, 3, True)(x)  
x = Capsule(32, 8, 3, True)(x)   
capsule = Capsule(2, 16, 3, True)(x)
output = Lambda(lambda z: K.sqrt(K.sum(K.square(z), 2)))(capsule)


#model2: model with pre-training
input_image2 = Input(shape=(None, None, 3))
x2 = Conv2D(64, (3, 3), activation='relu')(input_image2)
x2=BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True, beta_initializer='zeros', gamma_initializer='ones', moving_mean_initializer='zeros', moving_variance_initializer='ones', beta_regularizer=None, gamma_regularizer=None, beta_constraint=None, gamma_constraint=None)(x2)
x2 = Conv2D(64, (3, 3), activation='relu')(x2)
x2 = AveragePooling2D((2, 2))(x2)
x2 = Conv2D(128, (3, 3), activation='relu')(x2)
x2 = Conv2D(128, (3, 3), activation='relu')(x2)




x2 = Reshape((-1, 128))(x2)
x2 = Capsule(32, 8, 3, True)(x2)  
x2 = Capsule(32, 8, 3, True)(x2)   
capsule2 = Capsule(2, 16, 3, True)(x2)
output2 = Lambda(lambda z: K.sqrt(K.sum(K.square(z), 2)))(capsule2)




model = Model(inputs=[input_image], outputs=[output])
model2 = Model(inputs=[input_image2], outputs=[output2])



model.load_weights('My Drive/Colab Notebooks/215-FP_Dataset/after-train.h5')
model2.load_weights('My Drive/Colab Notebooks/215-FP_Dataset/weights-improvement-binary-after-44.h5')

predict=model.predict([x_test])
predict=np.argmax(predict,axis=1)

predict2=model2.predict([x_test])
predict2=np.argmax(predict2,axis=1)


summation1=0




In [47]:
y_test=np.argmax(y_test,axis=1)
y_test[0:100]

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [48]:
predict[0:100]

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [ ]:
'''from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
predict=np.array(predict)
label_encoder = LabelEncoder()
predict = label_encoder.fit_transform(predict)
predict



onehot_encoder = OneHotEncoder(sparse=False)
predict = predict.reshape(len(predict), 1)
predict = onehot_encoder.fit_transform(predict)
predict

predict2=np.array(predict2)
label_encoder = LabelEncoder()
predict2 = label_encoder.fit_transform(predict2)
predict2
onehot_encoder = OneHotEncoder(sparse=False)
predict2 = predict2.reshape(len(predict2), 1)
predict2 = onehot_encoder.fit_transform(predict2)
predict2'''


In [63]:
accuracy_before=0
specificity_before=0
sensitivity_before=0
precision_before=0
f1_before=0
newaccuracy=0
from __future__ import print_function
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Layer
from tensorflow.keras import activations
from tensorflow.keras import utils
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
import numpy as np
import keras
from sklearn.metrics import roc_curve, auc
from matplotlib import pyplot as plt

summation1=0

for i in range(len(x_test)):
    if predict[i]==y_test[i]:
        summation1=summation1+1
print('accurate predictions: ',summation1) 
print('Total predictions to be made in testing :', len(x_test))     
accuracy_before=summation1/len(x_test)



summation1=0
summation2=0
summation3=0
summation4=0

for i in range(len(x_test)):
    if predict[i]==y_test[i] and y_test[i]==0:
        summation1=summation1+1
        
specificity_before=summation1/np.count_nonzero(y_test==0)

for i in range(len(x_test)):
    if predict[i]==y_test[i] and y_test[i]==1:
        summation2=summation2+1
        
sensitivity_before=summation2/np.count_nonzero(y_test==1)

for i in range(len(x_test)):
    if predict[i]!=y_test[i] and y_test[i]==1:
        summation3=summation3+1

for i in range(len(x_test)):
    if predict2[i]!=y_test[i] and y_test[i]==0:
        summation4=summation4+1


precision_before=summation1/(summation1+summation3)
newaccuracy=((summation1+summation2)/(summation1+summation2+summation3+summation4))
f1_before=2*((sensitivity_before*precision_before)/(sensitivity_before + precision_before))
#print("TN: ",summation1,", TP : ",summation2,", FP:",summation3, ", FN :",summation4)
print('accuracy : ',accuracy_before)
print('specificity  : ',specificity_before)
print('sensitivity or precision  : ',sensitivity_before)
print('precision  : ', precision_before)
print('f1-score  : ', f1_before)
#print('newaccuracy : ',newaccuracy)




accurate predictions:  1498
Total predictions to be made in testing : 1507
accuracy :  0.9940278699402787
specificity  :  0.9960745829244357
sensitivity or precision  :  0.9897540983606558
precision  :  0.9950980392156863
f1-score  :  0.9924188748760097
